### ISSUE TITLE
codepipeline notification

### ISSUE THREAD

**Issue by williamputraintan** [umccr/orcabus#113]
add pipeline notification to slack for failed/successful deployment

not critical as now is in dev mode, but might be useful to know if the pipeline is failing

**Comment by victorskl** [comment]
Good ticket, Will. I'd vote higher priority (see in the board).


_(p.s. meant to mention this; we plan to use label more effectively in automation with project board. in this case, i'd recommend you label "platform" that will automatically add into "OrcaBus: Platform" GH board. Since, we are using label; we can avoid prefix in issue ticket such that "pipeline:" would not be necessary)_

FYI too @mmalenic

**Comment by victorskl** [comment]
Also this should be "platform". Not "pipeline".

**Comment by victorskl** [comment]
FYI too @reisingerf @alexiswl @brainstorm

**Comment by victorskl** [comment]
As an example, pls see #106

**Comment by williamputraintan** [comment]
currently deployed to bastion account and it seems that the account there do not have slack configured in the AWS Chatbot. I'm happy to configure this, unless I am missing permission from slack? @victorskl @reisingerf

**Comment by victorskl** [comment]
(note to self) This is on the basis of such that still using our exisiting AWS ChatBot Slack notification infrastructure. As this is still on bastion account.
