### ISSUE TITLE
Metadata: Project Owner / Project ID attributes not found in metadata manager

### ISSUE THREAD

**Issue by alexiswl** [umccr/orcabus#446]
Is this by design? Thought that these would be good to have as tags for workflow run events / downstream processing such as DataBricks would be able to sort data by these attributes

**Comment by alexiswl** [comment]
Related to https://github.com/umccr/orcabus/issues/439

**Comment by williamputraintan** [comment]
Initially yes? So we thought that the Project Owner/Id is not needed to determine the execution logic for a particular library. But perhaps these values should still be somehow accessible to the OrcaBus, so possibly to put back in the metadata manager. 

cc: @reisingerf

**Comment by reisingerf** [comment]
The current definition of "project" is rather vague and overloaded. It's not bound to any particular purpose. I was hoping we can create better metadata attributes that are better suited and more for a particular purpose, instead of using what's there even if it's not a good match. 
We can put those back in if they are needed, but I'd rather add attributes for a particular purpose. (mind you, outside of the orcabus metadata service we have not real place for that yet)

**Comment by alexiswl** [comment]
This was related to the data sharing story, I can always use the gspread pandas secret if need be so that the orcabus metadata isn't affected. Once we know what the alternative to project owner / project id is then we can move to making those events instead
