### ISSUE TITLE
filemanager: add presigned URL route

### ISSUE THREAD

**Issue by mmalenic** [umccr/orcabus#459]
The orcabus UI needs access to presigned URLs for fetching objects. A new route could be added for a single object/multiple objects by key:

* `/api/v1/s3_objects/presign/{:id}`
* `/api/v1/s3_objects/presign?key=...`.
    * This could support any of the query filter parameters.
    * Should it also support pagination?

This could return a response with a single URL (and potentially a redirect?) or multiple URLs in the case of a collection of objects:
```json
{
    "results": [ "<presigned_urls...>" ]
}
```

**Comment by williamputraintan** [comment]
On the presign object topic, just a feature request so that it allows to accept [content-disposition](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition) in header/query params so that is viewable friendly in web. Perhaps `attachment` is the default and `inline` is something to specify.

Related current portal closed issue: https://github.com/umccr/data-portal-apis/issues/142
